# Change these first
owner: Skiddle-ID # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: Main Website
    url: https://skiddle.id
  - name: Private Wiki (wiki.skiddle.id)
    url: https://wiki.skiddle.id
  - name: Private Mastodon (chat.skiddle.id)
    url: https://chat.skiddle.id
    expectedStatusCodes:
      - 200
      - 201
      - 404
      - 503
  - name: Mail System
    url: https://skiddle.id
  - name: Wordpress Blog
    url: https://skiddle.my.id
  - name: Skiddle Network
    url: https://skiddle.network
  - name: Skiddle Network Gateway
    url: https://skiddle.cloudflareaccess.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.skiddle.id
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Skiddle Status Monitoring
  introTitle: "**Skiddle-ID** current network status. "
  introMessage: This page for Monitoring status of all Skiddle-ID Network.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
commitMessages:
  commitAuthorName: "Laurensius Jeffrey"
  commitAuthorEmail: "vrusolik@gmail.com"
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
